### ISSUE TITLE
Intentional [bs-form-group] should be priority as a parent, than .form-group

### ISSUE THREAD

**Issue by vip9** [sagrawal14/bootstrap-angular-validation#29]
When you are using bs-form-group property, you put it purposely, so module should take it as a priority in getFormGroupElement. and not to try to first search for .form-group.

**Comment by sagrawal31** [comment]
Thanks for raising this! Sometimes we can't use the `.form-group` class as the parent of any input field based on the UI design needed. For those cases, one can use the `bs-form-group` attribute to tell this library about the parent element. So there is no any intentional priority of checking the `.form-group` class at first hand.

May I know the reason why do you want to search `bs-form-group` attribute before `.form-group` class?

**Comment by vip9** [comment]
Broken template css design (two inputs in one form-group to achieve columns).
So I'm in the state, that .form-group exists, but I want to use other parent anyway.

**Comment by sagrawal31** [comment]
@vip9 you were right! I saw the requirement of giving priority to `[bs-form-group]` selector over `.form-group` selector. I fixed it and released in [v1.0.7](https://github.com/sagrawal31/bootstrap-angular-validation/releases/tag/v1.0.7). Thanks for the support.
