### ISSUE TITLE
Keep it Simple keep it Clean

### ISSUE THREAD

**Issue by julianbei** [sagrawal14/bootstrap-angular-validation#8]
The request interception might be a useful feature in some cases.
From my perspective these cases are quite rare.
Therefore i suggest to not bloat this module with several edge and special cases.
A clean module which does:
- add missing validations to angulars standard validations set.
- add a directive which watches the "validity" of a single [ form > form-group > form-control] and conditionally add and remove bootstrap classes and error messages

that would be more then enough and as simple that everyone understands what it does.

**Comment by sagrawal31** [comment]
Thanks for raising this concern @julianbei . In my case, that interceptor is being used every time since the form content of my pages are loaded via templates (for example: the form elements for adding a new customer and editing an existing customer is same, so I made the form elements excluding the form generic and load it via another template).

But you are right. There is no point of loading that code so I've moved it to a separate file so that it can be added optionally.

Will be releasing the new version soon.
